markdown: redcarpet
name: Kristian's coding adventures
lsi: false
highlighter: pygments

name: Kristian's coding adventures
description: Thoughts of an iOS developer
url: http://kristian.co
timezone: Europe/Copenhagen
encoding: utf-8

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"